# Generated by Django 3.2.13 on 2023-08-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0002_livestream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
